config/routes.rb
Murphey::Application.routes.draw do

  get "logout" => 'users#destroy', as: :logout
  resources :menues
  resources :items
  resources :categories
  resources :users
  resources :reviews
  root to: "menues#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :category_id, :cost, :name
  
  belongs_to :category
  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :body, :item_id, :rating, :title, :user_id
  
  belongs_to :user
  belongs_to :item
  
  validates :rating, :numericality => {   :greater_than_or_equal_to => 0,
                                          :less_than_or_equal_to => 5 }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :login, :password
  
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :show_session_data
   before_filter :find_logged_in_user

   def find_logged_in_user
     @user = User.find_by_id(session[:login_id])
   end

   def show_session_data
     logger.debug "---------------------------"
     logger.debug "Session: #{session.inspect}"
     logger.debug "-" * 50
   end
    
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def show
    @category = Category.find(params[:id])
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController 
  
  def show 
    @item = Item.find(params[:id])
  end
  
  def new
    @item = Item.new
    @category = Category.all
  end
  
  def create
    @item = Item.new(params[:item])
    if @item.save
      redirect_to root_url, notice: "Item Added!" 
    else
      render new
    end
  end
  
end

app/controllers/menues_controller.rb
class MenuesController < ApplicationController
  def index
    @item = Item.all
  end
  
  def new
    @item = Item.new
    @category = Category.all
  end

  def create
    @item = Item.create(params[:item])
    if @item.save?
      redirect_to root_url, notice: "Item Added!"
    else
      render new
    end
  end
    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end
  
  def new
    @review = Review.new
    @item = Item.all
    
    @users = User.all
  end
  
  def create 
    @review = Review.new(params[:review])
    if @review.save
      redirect_to root_url, notice: "Review Added!" 
    else
      redirect_to new_review_url, notice: "Rating Must Be Between 0-5"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  
  def new
  end
  
  def destroy
    session[:login_id] = nil
    flash[:notice] = "See You Later"
    redirect_to root_url 
  end

    def create
      user = User.find_by_login(params[:login])

      if user
        if user.password_digest == params[:password]
          session[:login_id] = user
          redirect_to root_url 
        else
          redirect_to "/users/new", notice: "Bad password!"
        end
      else
        redirect_to "/users/new", notice: "Bad login ID!"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<% @category.items.each do |x| %>
<p>	<%= link_to x.name, item_url(x.id) %> costs <%= number_to_currency(x.cost) %></p>
	<% end %>
	

app/views/items/show.html.erb
<h1>
	<b><%= link_to @item.category.name, category_url(@item.category.id) %></b>
</h1>

<p><%= @item.name %> costs <%= number_to_currency(@item.cost) %></p>

<h2>Reviews</h2>
<% @item.reviews.each do |r| %>
<p><b><%= r.user.login %>:</b> <%= r.body %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Murphey</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="header">
		<h1><%= link_to "Murpheys Menu", root_url %></h1>
			<% if session[:login_id] %>
			<p>Hi <%= @user.login %>! Thanks for checking out Murpheys!</p> 
			<%= link_to "Rate an Item", new_review_url %> | 
			<%= link_to "Add A New Item", new_menue_url %> | 
			<%= link_to "Logout", logout_url %> 
			<% else %>
			<p>Please Login to Rate and Add Items!</p>
			<%= link_to "Login", new_user_url %>
			<% end %>
	</div>

	<% if flash[:notice] %>
	  <p style="color: white; background: red; padding: 4px">
	  <%= flash[:notice] %>
	  </p>
	<% end %>

<%= yield %>

</body>
</html>

app/views/menues/index.html.erb
<div>
	<table style="text-align:center">
		<thead style="text-align:center">
			<tr>
				<th>Type</th>
				<th>Name</th>
				<th>Cost</th>
				<th>Avg. Rating</th>
			</tr>
		</thead>
		<tbody>	
	<% @item.sort{ |a,b| a.category.name <=> b.category.name }.each do |item| %>
			<tr style="text-align:center">
				<td><%= link_to item.category.name, category_url(item.category.id) %></td>
				<td><%= link_to item.name, item_url(item.id) %></td>
				<td><%= number_to_currency(item.cost) %></td>
				<td><%= item.reviews.average("rating") %></td>
			</tr>
		<% end %>
		</tbody>
	</table>	
</div>

app/views/menues/new.html.erb
<%= form_for @item do |x| %>

<p>
	<%= x.label "Category" %>
	<%= x.collection_select(:category_id, @category, :id, :name) %>
</p>

<p>	
	<%= x.label :name %>
	<%= x.text_field :name %>
</p>
	
<p>	
	<%= x.label :cost %>
	<%= x.number_field :cost %>
</p>

	<%= x.submit "Add Your Item" %>
<% end %>

app/views/reviews/new.html.erb
<%= form_for @review do |x| %>

<p>
	<%= x.label "Item" %>
	<%= x.collection_select(:item_id, @item, :id, :name) %>
</p>

<p>
	<%= x.label "User" %>
	<%= x.collection_select(:user_id, @users, :id, :login	) %>
</p>

<p>	
	<%= x.label :title %>
	<%= x.text_field :title %>
</p>
	
<p>	
	<%= x.label :rating %>
	<%= x.number_field :rating %>
</p>

<p>	
	<%= x.label :body %>
	<%= x.text_area :body, :rows => 4 %>
</p>

	<%= x.submit "Add Your Item" %>
<% end %>

app/views/users/new.html.erb
<h1>Log In Here</h1>
<%= form_tag users_url do || %>
<p>	
	<%= label_tag :login %>
	<%= text_field_tag :login %>
</p>
	
<p>	
	<%= label_tag :password %>
	<%= password_field_tag :password %>
</p>	

	<%= submit_tag "Let Me In!" %>
	
<% end %>